/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSponsorsRouteImport } from './routes/_authenticated/sponsors'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedMentorsRouteImport } from './routes/_authenticated/mentors'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedInternshipsRouteImport } from './routes/_authenticated/internships'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSponsorsRoute = AuthenticatedSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorsRoute = AuthenticatedMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternshipsRoute =
  AuthenticatedInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/verify': typeof VerifyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/mentors': typeof AuthenticatedMentorsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/verify': typeof VerifyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/mentors': typeof AuthenticatedMentorsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/internships': typeof AuthenticatedInternshipsRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/mentors': typeof AuthenticatedMentorsRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sponsors': typeof AuthenticatedSponsorsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/verify'
    | '/analytics'
    | '/certificates'
    | '/community'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/internships'
    | '/marketing'
    | '/mentors'
    | '/outreach'
    | '/settings'
    | '/sponsors'
    | '/templates'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/verify'
    | '/analytics'
    | '/certificates'
    | '/community'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/internships'
    | '/marketing'
    | '/mentors'
    | '/outreach'
    | '/settings'
    | '/sponsors'
    | '/templates'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/events'
    | '/verify'
    | '/_authenticated/analytics'
    | '/_authenticated/certificates'
    | '/_authenticated/community'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/internships'
    | '/_authenticated/marketing'
    | '/_authenticated/mentors'
    | '/_authenticated/outreach'
    | '/_authenticated/settings'
    | '/_authenticated/sponsors'
    | '/_authenticated/templates'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sponsors': {
      id: '/_authenticated/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthenticatedSponsorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentors': {
      id: '/_authenticated/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof AuthenticatedMentorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships': {
      id: '/_authenticated/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AuthenticatedInternshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedInternshipsRoute: typeof AuthenticatedInternshipsRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMentorsRoute: typeof AuthenticatedMentorsRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSponsorsRoute: typeof AuthenticatedSponsorsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedInternshipsRoute: AuthenticatedInternshipsRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMentorsRoute: AuthenticatedMentorsRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSponsorsRoute: AuthenticatedSponsorsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
